"""empty message

Revision ID: 4ae6b3267961
Revises: d7a02fef950a
Create Date: 2026-02-27 14:45:31.921220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae6b3267961'
down_revision = 'd7a02fef950a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'brand', ['brand'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('brand')

    op.drop_table('brand')
    # ### end Alembic commands ###
