"""empty message

Revision ID: aebc12e0b68f
Revises: 9f5f8dd570e5
Create Date: 2026-02-26 12:27:40.135764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aebc12e0b68f'
down_revision = '9f5f8dd570e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cust_name', sa.String(length=200), nullable=False),
    sa.Column('cust_email', sa.String(length=150), nullable=False),
    sa.Column('cust_phone', sa.String(length=15), nullable=True),
    sa.Column('cust_datereg', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cust_id'),
    sa.UniqueConstraint('cust_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
